sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t hans/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hans/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: elasticbeanstalk-eu-central-1-458471041185
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY